name: ingilizce_ogrenme_uygulamasi
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.4
  shared_preferences: ^2.2.2
  flutter_rating_bar: ^4.0.0
  url_launcher: ^6.1.7
  share_plus: ^7.2.1
  flutter_card_swiper: ^7.0.0
  swipe_cards: ^2.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/merged.json
    - assets/oxford.png

flutter_native_splash:
  android: true
  ios: true
  image: "assets/oxford.png"
  color: "#ffffff"
  background_image_android: "assets/oxford.png"
  background_image_dark_android: "assets/oxford.png"
  background_image_ios: "assets/oxford.png"
  background_image_dark_ios: "assets/oxford.png"
  android_12:
    image: assets/oxford.png
    color: "#ffffff"
    icon_background_color: "#ffffff"
    image_dark: assets/oxford.png
    color_dark: "#ffffff"
    icon_background_color_dark: "#ffffff"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/oxford.png"
  remove_alpha_ios: true